### ISSUE TITLE
Maske zur Erfassung von Projekten und dafür relevanten Skills

### ISSUE THREAD

**Issue by timo2o1o** [doerffler/accounting-control-center#5]
Als Projektmanager möchte ich mit der Anwendung Projekte erfassen können. Den Projekten sollen dort benötigte Skills zugeordnet werden, damit aus den Informationen später Mitarbeiterprofile generiert werden können.

Akkzeptanzkriterien:
Folgende Daten sollen erfasst werden können:
- [x] Projektname
- [x] Projektlaufzeit (Startdatum & Enddatum)
  - [x] Default Eintrag auf 'today' setzen
- [x] Dem Projekt sollen Aufträge zugeordnet werden können
  - [x] Zugeordnete Aufträge sollen aus der 'nicht Zugeordnet' Ansicht verschwinden.
  - [x] 'nicht Zugeordnet' aktualisierbar machen.
- [x] Dem Projekt zugeordnete Skills:

Es soll außerdem eine zweite Maske geben, in der Skills definiert werden können.
- [x] Skillname
- [x] Übergeordneter Skill (Es soll eine Kette aufbaubar sein: Technische Skills -> Programmiersprachen -> .Net -> C#)

![grafik](https://user-images.githubusercontent.com/8312711/165377363-4b317734-5c99-44c4-bd82-b9e5ab4bef2f.png)

**Comment by Jusdon** [comment]
![image](https://user-images.githubusercontent.com/34418811/221821854-61fee7f2-e578-4985-9cfa-bc9b59068574.jpeg)
