### ISSUE TITLE
Charts to display remaining budget on orders

### ISSUE THREAD

**Issue by timo2o1o** [doerffler/accounting-control-center#55]
**Is your feature request related to a problem? Please describe.**
To keep track of every order's remaining budget there should be diagrams on the application's main window. They should be aligned beneath a tab called "Auftragsstatus".

**Describe the solution you'd like**
There should be a combobox on top of the tab, that lets the user chose a business year. By default the current business year (so the business year which includes the current date) should be chosen. If a business year is selected all orders assigned to it should be displayed as burndown charts. Like this:
![grafik](https://user-images.githubusercontent.com/8312711/191466564-38380396-b094-4a38-9d5d-cedc428cf9ae.png)

**Acceptance criteria**
- [x] All functionality used for the charts is written in a "DisplayAuftragsstatusViewModel", which gets bind to the tabcontrol on the MainWindow
- [x] Ability to chose a business year
- [x] Every order's remaining budget gets drawn to a chart
- [x] All positions of the order are visualized as a bar
- [x] Every bar of a chart (so every order position) got its own color.
- [x] A line is drawn for every order position, which indicates the budget that should remain if the complete budget of the position would be used at the orders end date.
- [x] The color of the line is the same as its corresponding bar
- [x] A button is available that opens a window to display the data used for the diagrams in a datagrid
- [x] The datagrid's data can be exported to a csv- or xlsx-file (xlsx is optional)
- [x] The concrete data values can be retrieved by hovering the Chart (mouse over)

**Describe alternatives you've considered**
There should also be a possibility to show the data displayed in the charts in a datagrid that is exportable to csv or excel.

Here is the data model I considered for the charting:
<html>
<head>

</head>
<body>

Datum | Auftragsname | Auftragsposition | Restbudget_Ist | Restbudget_Soll
-- | -- | -- | -- | --
2022-01-31 | Softdisk: Gamer's Edge Q1 1991 | Implement Game Engine | 600 | 660
2022-01-31 | Softdisk: Gamer's Edge Q1 1991 | Draw Character Graphics | 800 | 750
2022-02-28 | Softdisk: Gamer's Edge Q1 1991 | Implement Game Engine | 500 | 520
2022-02-28 | Softdisk: Gamer's Edge Q1 1991 | Draw Character Graphics | 500 | 600
2022-03-31 | Softdisk: Gamer's Edge Q1 1991 | Implement Game Engine | 250 | 380
2022-03-31 | Softdisk: Gamer's Edge Q1 1991 | Draw Character Graphics | 400 | 450

</body>
</html>

**Comment by Jusdon** [comment]
yes of course I can do
