### ISSUE TITLE
Erstellen eines kompletten Testdatensatzes für das Datenmodell

### ISSUE THREAD

**Issue by timo2o1o** [doerffler/accounting-control-center#9]
Als Anwendungsentwickler brauche ich einen umfangreichen Testdatensatz, der alle Funktionen des Datenmodells nutzt. Dies hilft mir bei meinen Entwicklungstests.

**Comment by Jusdon** [comment]
@timo2o1o 

Maybe we can use this package to help with that. This makes the creation of test data much easier...

[Faker.NET](https://github.com/Kuree/Faker.Net)

**Comment by Jusdon** [comment]
@timo2o1o 

Maybe we can use this package to help with that. This makes the creation of test data much easier...

[Faker.NET](https://github.com/Kuree/Faker.Net)

**Comment by timo2o1o** [comment]
> @timo2o1o
> 
> Maybe we can use this package to help with that. This makes the creation of test data much easier...
> 
> [Faker.NET](https://github.com/Kuree/Faker.Net)

Thats is a good idea, we should try that out!

**Comment by timo2o1o** [comment]
> @timo2o1o
> 
> Maybe we can use this package to help with that. This makes the creation of test data much easier...
> 
> [Faker.NET](https://github.com/Kuree/Faker.Net)

This seems to be the better evolved faker.js port for .Net:
https://github.com/bchavez/Bogus

**Comment by timo2o1o** [comment]
I created some test data for outgoing invoices. For now only incoming invoices needs some new test data. But I'll create a new issue for that, since the data model for incoming invoices is not final yet.
